apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emr-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: eregister-storage-class
  volumeName: emr-persistent-volume
