apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eregister-storage-class
provisioner: microk8s.io/hostpath
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
